# Generated by Django 3.1.2 on 2020-11-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20201029_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='image',
            field=models.ImageField(upload_to='post_image'),
        ),
    ]
