# Generated by Django 3.1.2 on 2020-11-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_auto_20201103_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_image/'),
        ),
    ]
